<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\RekamMedis;
use Illuminate\Support\Carbon;

class RekamMedisSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'no_rekam_medis'            => 'RM-2026-0001',
                'nama_pasien'               => 'Siti Aminah',
                'usia'                      => 28,
                'no_telepon'                => '081234567890',
                'alamat'                    => 'Jl. Melati No. 12, Bandung',
                'golongan_darah'            => 'O',
                'kategori'                  => 'Kehamilan',
                'usia_kehamilan_minggu'     => 24,
                'hpht'                      => '2025-10-01',
                'taksiran_persalinan'       => '2026-07-08',
                'status_risiko'             => 'Rendah',
                'status_kunjungan'          => 'Aktif',
                'tekanan_darah'             => '110/70',
                'berat_badan'               => 62.5,
                'tinggi_badan'              => 158.0,
                'catatan_medis'             => 'Kondisi ibu dan janin sehat, perkembangan normal. Tidak ada keluhan berarti.',
                'diagnosis'                 => 'Kehamilan normal trimester 2',
                'tindakan'                  => 'USG, pemeriksaan rutin, suplemen asam folat',
                'tanggal_kunjungan_terakhir'=> '2026-04-10',
                'jadwal_kontrol_berikutnya' => '2026-05-10',
                'dokter_pemeriksa'          => 'dr. Nurhaliza, SpOG',
            ],
            [
                'no_rekam_medis'            => 'RM-2026-0002',
                'nama_pasien'               => 'Dewi Kartika',
                'usia'                      => 32,
                'no_telepon'                => '082345678901',
                'alamat'                    => 'Jl. Anggrek No. 5, Bandung',
                'golongan_darah'            => 'A',
                'kategori'                  => 'Kehamilan',
                'usia_kehamilan_minggu'     => 36,
                'hpht'                      => '2025-07-15',
                'taksiran_persalinan'       => '2026-04-22',
                'status_risiko'             => 'Sedang',
                'status_kunjungan'          => 'Aktif',
                'tekanan_darah'             => '135/85',
                'berat_badan'               => 78.0,
                'tinggi_badan'              => 160.0,
                'catatan_medis'             => 'Tekanan darah sedikit tinggi, perlu monitoring ketat. Disarankan istirahat cukup.',
                'diagnosis'                 => 'Hipertensi gestasional ringan',
                'tindakan'                  => 'Monitoring tekanan darah, USG Doppler, edukasi diet rendah garam',
                'tanggal_kunjungan_terakhir'=> '2026-04-22',
                'jadwal_kontrol_berikutnya' => '2026-04-29',
                'dokter_pemeriksa'          => 'dr. Nurhaliza, SpOG',
            ],
            [
                'no_rekam_medis'            => 'RM-2026-0003',
                'nama_pasien'               => 'Rina Susanti',
                'usia'                      => 25,
                'no_telepon'                => '083456789012',
                'alamat'                    => 'Jl. Dahlia No. 8, Cimahi',
                'golongan_darah'            => 'B',
                'kategori'                  => 'Keluarga Berencana',
                'usia_kehamilan_minggu'     => null,
                'hpht'                      => null,
                'taksiran_persalinan'       => null,
                'status_risiko'             => 'Rendah',
                'status_kunjungan'          => 'Aktif',
                'tekanan_darah'             => '115/75',
                'berat_badan'               => 55.0,
                'tinggi_badan'              => 155.0,
                'catatan_medis'             => 'Konsultasi dan pemasangan IUD. Pasien dalam kondisi baik.',
                'diagnosis'                 => 'KB IUD',
                'tindakan'                  => 'Pemasangan IUD Copper T, edukasi pasca-pemasangan',
                'tanggal_kunjungan_terakhir'=> '2026-04-15',
                'jadwal_kontrol_berikutnya' => '2026-05-15',
                'dokter_pemeriksa'          => 'dr. Siti Rahayu, SpOG',
            ],
            [
                'no_rekam_medis'            => 'RM-2026-0004',
                'nama_pasien'               => 'Fatimah Zahra',
                'usia'                      => 30,
                'no_telepon'                => '084567890123',
                'alamat'                    => 'Jl. Mawar No. 3, Bandung',
                'golongan_darah'            => 'AB',
                'kategori'                  => 'Kehamilan',
                'usia_kehamilan_minggu'     => 38,
                'hpht'                      => '2025-07-01',
                'taksiran_persalinan'       => '2026-04-07',
                'status_risiko'             => 'Tinggi',
                'status_kunjungan'          => 'Dirujuk',
                'tekanan_darah'             => '155/100',
                'berat_badan'               => 82.0,
                'tinggi_badan'              => 162.0,
                'catatan_medis'             => 'Preeklampsia berat. Dirujuk ke RS untuk penanganan lebih lanjut.',
                'diagnosis'                 => 'Preeklampsia berat',
                'tindakan'                  => 'Stabilisasi, rujukan ke RSUD Bandung',
                'tanggal_kunjungan_terakhir'=> '2026-04-05',
                'jadwal_kontrol_berikutnya' => null,
                'dokter_pemeriksa'          => 'dr. Nurhaliza, SpOG',
            ],
            [
                'no_rekam_medis'            => 'RM-2026-0005',
                'nama_pasien'               => 'Lestari Wulandari',
                'usia'                      => 27,
                'no_telepon'                => '085678901234',
                'alamat'                    => 'Jl. Kenanga No. 15, Bandung',
                'golongan_darah'            => 'O',
                'kategori'                  => 'Kontrol Umum',
                'usia_kehamilan_minggu'     => null,
                'hpht'                      => null,
                'taksiran_persalinan'       => null,
                'status_risiko'             => 'Rendah',
                'status_kunjungan'          => 'Selesai',
                'tekanan_darah'             => '120/80',
                'berat_badan'               => 58.0,
                'tinggi_badan'              => 157.0,
                'catatan_medis'             => 'Kontrol pasca persalinan 6 minggu. Kondisi baik, pemulihan normal.',
                'diagnosis'                 => 'Post-partum normal',
                'tindakan'                  => 'Pemeriksaan fisik, konseling ASI eksklusif',
                'tanggal_kunjungan_terakhir'=> '2026-04-20',
                'jadwal_kontrol_berikutnya' => null,
                'dokter_pemeriksa'          => 'dr. Siti Rahayu, SpOG',
            ],
            [
                'no_rekam_medis'            => 'RM-2026-0006',
                'nama_pasien'               => 'Anisa Putri',
                'usia'                      => 22,
                'no_telepon'                => '086789012345',
                'alamat'                    => 'Jl. Tulip No. 9, Cimahi',
                'golongan_darah'            => 'A',
                'kategori'                  => 'Konsultasi',
                'usia_kehamilan_minggu'     => null,
                'hpht'                      => null,
                'taksiran_persalinan'       => null,
                'status_risiko'             => 'Rendah',
                'status_kunjungan'          => 'Selesai',
                'tekanan_darah'             => '118/76',
                'berat_badan'               => 52.0,
                'tinggi_badan'              => 154.0,
                'catatan_medis'             => 'Konsultasi siklus menstruasi tidak teratur. Disarankan pola hidup sehat.',
                'diagnosis'                 => 'Oligomenorrhea',
                'tindakan'                  => 'Edukasi gizi, vitamin D, kontrol 1 bulan',
                'tanggal_kunjungan_terakhir'=> '2026-04-25',
                'jadwal_kontrol_berikutnya' => '2026-05-25',
                'dokter_pemeriksa'          => 'dr. Siti Rahayu, SpOG',
            ],
        ];

        foreach ($data as $item) {
            RekamMedis::create($item);
        }
    }
}
